language: android

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
  - ./gradlew compileDebugSources
