language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - android-25
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew lint
  - ./gradlew test
  - ./gradlew assembleDebug

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
